#Web Server
server:
    port: 9000

#Database
spring:
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/webirpf
        username: seeker
        password: seeker
        driverClassName: com.mysql.jdbc.Driver